//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.07 at 07:25:01 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://reqres.data.ws.akash.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.akash.ws.data.reqres;
