
package com.akash.ws.client.stub.fileupload;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "FileUploadWsdlServicePortService", targetNamespace = "http://data.ws.akash.com/schema/fileupload", wsdlLocation = "file:/E:/LALA/oodles/new_projects/MySpringWS/src/main/webapp/wsdl/FileUploadWsdlService.wsdl")
public class FileUploadWsdlServicePortService
    extends Service
{

    private final static URL FILEUPLOADWSDLSERVICEPORTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.akash.ws.client.stub.fileupload.FileUploadWsdlServicePortService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.akash.ws.client.stub.fileupload.FileUploadWsdlServicePortService.class.getResource(".");
            url = new URL(baseUrl, "file:/E:/LALA/oodles/new_projects/MySpringWS/src/main/webapp/wsdl/FileUploadWsdlService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/E:/LALA/oodles/new_projects/MySpringWS/src/main/webapp/wsdl/FileUploadWsdlService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        FILEUPLOADWSDLSERVICEPORTSERVICE_WSDL_LOCATION = url;
    }

    public FileUploadWsdlServicePortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileUploadWsdlServicePortService() {
        super(FILEUPLOADWSDLSERVICEPORTSERVICE_WSDL_LOCATION, new QName("http://data.ws.akash.com/schema/fileupload", "FileUploadWsdlServicePortService"));
    }

    /**
     * 
     * @return
     *     returns FileUploadWsdlServicePort
     */
    @WebEndpoint(name = "FileUploadWsdlServicePortSoap11")
    public FileUploadWsdlServicePort getFileUploadWsdlServicePortSoap11() {
        return super.getPort(new QName("http://data.ws.akash.com/schema/fileupload", "FileUploadWsdlServicePortSoap11"), FileUploadWsdlServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FileUploadWsdlServicePort
     */
    @WebEndpoint(name = "FileUploadWsdlServicePortSoap11")
    public FileUploadWsdlServicePort getFileUploadWsdlServicePortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://data.ws.akash.com/schema/fileupload", "FileUploadWsdlServicePortSoap11"), FileUploadWsdlServicePort.class, features);
    }

}
