//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.03 at 10:55:19 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://data.ws.akash.com/schema/employee", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.akash.ws.server.employee.stub;
