
package com.akash.ws.service.schema;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "LoginServiceService", targetNamespace = "http://reqres.data.ws.akash.com", wsdlLocation = "file:/E:/LALA/oodles/new_projects/MySpringWS/src/main/webapp/wsdl/loginmanager.wsdl")
public class LoginServiceService
    extends Service
{

    private final static URL LOGINSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.akash.ws.service.schema.LoginServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.akash.ws.service.schema.LoginServiceService.class.getResource(".");
            url = new URL(baseUrl, "file:/E:/LALA/oodles/new_projects/MySpringWS/src/main/webapp/wsdl/loginmanager.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/E:/LALA/oodles/new_projects/MySpringWS/src/main/webapp/wsdl/loginmanager.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        LOGINSERVICESERVICE_WSDL_LOCATION = url;
    }

    public LoginServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoginServiceService() {
        super(LOGINSERVICESERVICE_WSDL_LOCATION, new QName("http://reqres.data.ws.akash.com", "LoginServiceService"));
    }

    /**
     * 
     * @return
     *     returns LoginService
     */
    @WebEndpoint(name = "LoginServiceSoap11")
    public LoginService getLoginServiceSoap11() {
        return super.getPort(new QName("http://reqres.data.ws.akash.com", "LoginServiceSoap11"), LoginService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoginService
     */
    @WebEndpoint(name = "LoginServiceSoap11")
    public LoginService getLoginServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://reqres.data.ws.akash.com", "LoginServiceSoap11"), LoginService.class, features);
    }

}
