//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.30 at 08:34:56 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://reqres.data.ws.akash.com/userdetails", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.akash.ws.server.userdetails.stub;
