//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.03 at 10:56:49 PM IST 
//


package com.akash.ws.server.userdetails.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fullUserDetails" type="{http://data.ws.akash.com/schema/userdetails}fullUserDetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fullUserDetails"
})
@XmlRootElement(name = "UserDetailsResponse")
public class UserDetailsResponse {

    @XmlElement(required = true)
    protected FullUserDetails fullUserDetails;

    /**
     * Gets the value of the fullUserDetails property.
     * 
     * @return
     *     possible object is
     *     {@link FullUserDetails }
     *     
     */
    public FullUserDetails getFullUserDetails() {
        return fullUserDetails;
    }

    /**
     * Sets the value of the fullUserDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link FullUserDetails }
     *     
     */
    public void setFullUserDetails(FullUserDetails value) {
        this.fullUserDetails = value;
    }

}
